### ISSUE TITLE
redirects through resources.usgin.org don't honor accept headers

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/digital-crust-LDR#4]
http://resources.usgin.org/uri-gin/dtr/class/attribute/observednumericvalue will 303 redirect to 
http://23.23.228.241:32781/class/attribute/observednumericvalueminimum and return html, the default representation.
If I use a REST client and attach an 'accept=text/html' header, either of these will work, but if I use any of the other MIME types allowed by UK LOD (see https://github.com/UKGovLD/registry-core/wiki/Api#content-negotiation) e.g. text/turtle, application/rdf+xml, application/ld+json, text/csv they all work if the request goes to 23.23.228.241, but if they go to resources.usgin.org I get a "406 Error: Not Acceptable".  @jessica-azgs  can you check on the URI redirector and see if it needs to be configured to pass the accept header through. I'm pretty sure Ryan build it to allow content negotiation.

**Comment by jessicagood** [comment]
Ok, fixed. Added the mime types: text/turtle, application/rdf+xml, application/ld+json and text/csv.
