### ISSUE TITLE
Ontologies

### ISSUE THREAD

**Issue by jessicagood** [usgin/digital-crust-LDR#5]
@smrazgs I was finally able to upload the [Ontology graph](https://github.com/usgin/digital-crust-LDR/blob/master/Ontologies/datatype.ttl) that you created several weeks ago. I renamed your file `Ontologies/datatype.ttl` but otherwise I changed very little. I changed the URIs slightly and added `rdfs:label` to the main entity. How does it look? What do you want changed?

http://resources.usgin.org/uri-gin/dtr/ont/datatype

**Comment by smrgeoinfo** [comment]
Jess-- looks good for now. I'll close this, and open new issues if something comes up.
